#################################################################################################################################
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
# ________  ________  ________   ___  __    ________       ___    ___             ___  ___  ________  _____ ______   _______
#|\   __  \|\   __  \|\   ___  \|\  \|\  \ |\   ____\     |\  \  /  /|           |\  \|\  \|\   __  \|\   _ \  _   \|\  ___ \
#\ \  \|\ /\ \  \|\  \ \  \\ \  \ \  \/  /|\ \  \___|_    \ \  \/  / /___________\ \  \\\  \ \  \|\  \ \  \\\__\ \  \ \   __/|
# \ \   __  \ \   __  \ \  \\ \  \ \   ___  \ \_____  \    \ \    / /\____________\ \   __  \ \  \\\  \ \  \\|__| \  \ \  \_|/__
#  \ \  \|\  \ \  \ \  \ \  \\ \  \ \  \\ \  \|____|\  \    \/  /  /\|____________|\ \  \ \  \ \  \\\  \ \  \    \ \  \ \  \_|\ \
#   \ \_______\ \__\ \__\ \__\\ \__\ \__\\ \__\____\_\  \ __/  / /                  \ \__\ \__\ \_______\ \__\    \ \__\ \_______\
#    \|_______|\|__|\|__|\|__| \|__|\|__| \|__|\_________\\___/ /                    \|__|\|__|\|_______|\|__|     \|__|\|_______|
#                                             \|_________\|___|/
#
##################################################################################################################################
## => Site Settings
##############################
title   : Banksy's Blog
url     : "https://Banksy-C.github.io" # the base hostname & protocol(协议) for your site e.g. https://www.someone.com
baseurl : "" # does not include hostname
tagline : Technical blog and notes for personal archive # 技术博客和个人档案笔记
#description: >
#Sharing technical knowledge in a easy-to-learn way
# 以易于学习的方式分享技术知识

bio-page-label: About
theme-home: theme-home-builtin-1.html
# Specify the rouge syntax highlighter theme. Pick one from css/rouge.
rouge-theme: igorpro
# NORMALLY NEVER CHANGE THE FOLLOWING（通常从不更改以下内容 ）
markdown: kramdown
include: [_data]

## => Language and Timezone
##############################
lang:  # the language of your site, default as "en"
timezone:  # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## => Author and Social
##############################
author:
  type      : person # "person" (default), "organization"
  name      : "Banksy"
  url       :
  avatar    : # path or url of avatar image (square)
  bio       :
  email     : banksy_c@163.com
  facebook  : # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  telegram  : # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  medium    : # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  zhihu     : # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  linkedin  : # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github    : https://github.com/Banksy-C # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: Banksy-C/Banksy-C.github.io
repository_tree: master

## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)

## license
license: CC-BY-NC-4.0 #非商业性:您可自由地分享和改编本作品，但您不得用于商业目的。
